name: CI - React SPA con E2E y Performance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-e2e-and-performance:
    runs-on: ubuntu-latest

    steps:
      - name:  Clonar repositorio
        uses: actions/checkout@v3

      - name:  Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name:  Instalar dependencias del proyecto
        run: npm install

      - name:  Levantar app en background
        run: |
          nohup npm run dev > vite.log 2>&1 &
          sleep 10

      - name:  Ejecutar pruebas E2E con Cypress
        run: |
          npx cypress run --headless

      - name:  Instalar Python y Locust
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name:  Instalar dependencias de Locust
        run: pip install locust

      - name:  Ejecutar Locust en modo headless
        run: |
          locust -f locustfile.py --host=http://localhost:5173 --headless -u 10 -r 5 -t 10s
